apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-for-gitops-config
  namespace: openshift-operators
spec:
  destination:
    namespace: default
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: okd-manifests
    repoURL: 'https://github.com/vrutkovs/okd-gitops-day1'
    targetRevision: HEAD
  syncPolicy:
    automated: {}
