kind: Secret
apiVersion: v1
metadata:
  name: htpasswd-6nc4p
  namespace: openshift-config
data:
  htpasswd: >-
    dnJ1dGtvdnM6JDJ5JDA1JFVWanlUZVhmc0l4VnE3ZTZBMzgzai5oVTZLSzhTTkVlM29xbUtjUGdGeEtWamtPbGpnM1NHCg==
type: Opaque
